### ISSUE TITLE
[bug][minor] Non-string value of `sorting-spec:` prevents the custom sorting from working w/o error message

### ISSUE THREAD

**Issue by SebastianMC** [SebastianMC/obsidian-custom-sort#119]
When the value of `sorting-spec:` is entered - by mistake - as an object, not as a string, the plugin stops from working. No error message is shown. Any attempt to enable custom sorting (ribbon icon, command, context menu) fails with no error message. Only JS exception is visible in developer console.

For example, missing the trailing pipe character `|` gives this effect:
```yaml
sorting-spec:
  target-folder: /*
  < a-z
```

For clarity, the correct version of the spec is:

```yaml
sorting-spec: |
  target-folder: /*
  < a-z
```

or

```yaml
sorting-spec: |-
  target-folder: /*
  < a-z
```

The latter form with `|-` is generated by the Obsidian properties editor.
