### ISSUE TITLE
[Feature Request] Separators

### ISSUE THREAD

**Issue by replete** [SebastianMC/obsidian-custom-sort#55]
This plugin works great, especially having a single `sortspec` to deal with manual sorting of the main navigation and pinning important notes to the top of lists.

I would love to be able to add in a UI separator to the file explorer view in my sortspec, something like this, using a simple `---` delimiter:

```
---
sorting-spec: |
    target-folder: Daily
    Tracker
    > a-z
    target-folder: /
    Home
    ---
    Daily
    Weekly
    Projects
    Notes
    ---
    Journal
    Dreams
    Thoughts
    Writing
    ---
    Assets
    Temporary
    ...
    z-a
---
```

This would create a separator in the workspace which would have markup like:

```html
<div class="nav-folder is-collapsed"/>
<div class="nav-separator">
    <div class="nav-separator-inner"></div>
 </div>
```

And CSS like:
```css
.nav-folder-separator {
display:block;
width:100%:
padding: var(--some-var) var(--some-var)
}
.nav-folder-separator-inner {
/* you get the idea*/
}
```

I could help with the markup/CSS part if this sounds like a good idea.

**Comment by SebastianMC** [comment]
Hi @replete

thanks for your feedback and input!

I also needed separators so I investigated the available options to generate them on-the-fly by the plugin. It turned out that technically it is not feasible or far too complicated to be worth it.

For example, following the idea which you described is not feasible because the **custom-sort** plugin, same as the Obsidian File Explorer, operates at the level of logical folders-files tree. The logical tree is a reflection of the underneath filesystem and the plugin only changes the order of items in the logical tree, on-the-fly. The rendering phase (generation of HTML DOM) for the File Explorer view is done later on by Obsidian, off the logical tree. It involves the idea of a virtual view, which displays only part of the logical tree, and as user scrolls the tree up and down, expands and collapses the folders, the relevant HTML elements are created and discarded as needed, based on the logical folders-files tree. The plugin is not connected to this HTML/DOM creation phase, it operates on an earlier stage on the logical files-folders tree. And keeping this single-point-of-integration of the plugin and Obsidian is essential to make it long-term compatible with future Obsidian releases.

I also exercised another option which was to inject in the folders-files tree some artificial notes with tile like '---' (or similar approach). I didn't work either because the File Explorer HTML/DOM rendering logic got fooled for some reason. Trying to render items non existing in the filesystem caused the view refresh problems and observable slowness. Strange, I didn't investigate it further.

Eventually I ended up with a **simple approach to explicitly create notes acting as separators**.
There is a nice unicode character [U+23AF Horizontal Line Extension](https://www.compart.com/en/unicode/U+23AF): `⎯` which can be used as note name, repeated as many times as wanted

Taking your example as an input, you could create three notes:
- `⎯` (a single character)
- `⎯⎯` (repeated 2x)
- `⎯⎯⎯` (repeated 3x)

Then, in the sorting specification include the names explicitly.
The result could look like:

![issue-55-separators](https://user-images.githubusercontent.com/23032356/218527870-91b12eb4-cb91-4dbe-994c-780208dc0eb4.jpg)

obviously for the titles you can use simple dashes, or the unicode line repeated more times, according to visual preferences

Not being ideal (the artificial notes need to exist in the vault), the approach works for me

At the same time, I'm keeping in mind the automatic generation of the separators. Maybe some new idea crosses my mind, if so I will give it a try.

**Comment by replete** [comment]
@SebastianMC Thank you for such a comprehensive answer.

I woke up and had an idea, and just made a very quick proof of concept:

![Screenshot 2023-02-14 at 11 20 00](https://user-images.githubusercontent.com/812139/218722197-fcb35f00-1ac9-425f-b2b5-2156c0a9a197.png)
```css
.nav-folder:nth-of-type(4) {
    margin-bottom:15px;
}

.nav-folder:nth-of-type(4)::after {
    content:'';
    display:block;
    height:1px;
    width:100%;
    background:var(--tx3);
    bottom:-9px;
    position:absolute;
}
```
If the plugin can apply a style hook (data-attribute or css class) for items that should have a separator _underneath_ them, then through use of the seemingly reliable css variables for metrics, I could write CSS that should work for most themes without adjustments. From a quick test, it works as expected, the CSS generated content (`::after`) requires no new markup and because it is absolutely positioned it is not included in box model of the item it is attached to.

If the plugin could figure out what element is above the separator and add a CSS class, then the problem is only styling.

As an aside, I've spent a week hacking CSS snippets to make all the plugins I want to use look better, so my first thought was 'Can I do this in just CSS?'

```css
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:has([data-path=Journal]),
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:has([data-path="Assets/Templater/Startup/skipFrontmatter.md"){
{
    outline: 2px solid red;
}
```
Almost - the `:has()` seems to fail, possibly due to out of spec or outdated rendering engine. 

Adding a `has-separator` CSS class or hook to navigation items through sortspec would be ideal, but I understand if this feels out of place

**Comment by replete** [comment]
For anyone else who stumbles upon this, this is my CSS hack for the time being to add separators to my main vault structure (which doesn't change much):

```css
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(2) {
    /* uncomment this out to test your selector */
    /* outline:1px solid red !important */
}

.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(2),
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(4),
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(6),
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(10),
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(12) {
    margin-bottom: 14px;
}

.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(2)::after,
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(4)::after,
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(6)::after,
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(10)::after,
.nav-folder.mod-root > .nav-folder-children > [class*=nav-]:nth-of-type(12)::after {
    content:'';
    display:block;
    height:1px;
    width:100%;
    bottom:-7px;
    left:-8px;
    background:linear-gradient(to right, var(--divider-color), transparent);
    position:absolute;
}
```
![Screenshot 2023-02-14 at 12 21 17](https://user-images.githubusercontent.com/812139/218737024-fd0ab0ee-df71-409c-befb-721c18d06f1d.png)
![Screenshot 2023-02-14 at 12 21 35](https://user-images.githubusercontent.com/812139/218737086-d5aebc3a-c4a0-48c3-89fc-2c0238a6ab55.png)
