### ISSUE TITLE
Tab character raises error instead of being treated as a whitespace

### ISSUE THREAD

**Issue by SebastianMC** [SebastianMC/obsidian-custom-sort#96]
This is reported in the [community forum](https://forum.obsidian.md/t/custom-file-explorer-sorting-cant-get-it-to-work-with-2-target-folders-anymore/66840) by [daddydave](https://forum.obsidian.md/u/daddydave)

The example described there is:
```yaml
---
sorting-spec: |
    target-folder: /
    order-asc: a-z
	
    target-folder: Reading
    order-desc: modified
---
```
the blank line contains >TAB< character, which is the source of the problem.

Investigate why and fix - tabs should be treated as whitespace

<img src="https://github.com/SebastianMC/obsidian-custom-sort/assets/23032356/d48e6897-8436-4102-98e5-4916ca7816bb" width="352">
